spring.application.name=sacco-management
spring.datasource.url=jdbc:postgresql://localhost:5432/sacco_management
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# A secure, random 256-bit string key (Must be at least 32 characters long)
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Token expiration timeframe in milliseconds (e.g., 24 hours)
app.jwt.expiration=86400000

